Add Financing
atInisiatifZakat/distribution-financings pull request #2
Opened 2024-10-28 09:21 UTC by nadiannisaqilah

2024-10-28 09:50 UTC, nuradiyana requested changes

2024-10-28 09:50 UTC, nuradiyana commented on database/migrations/2024_10_18_042326_create_distribution_financings_table.php
File name nya jadi `create_distribution_financings_table.php` aja

2024-10-28 09:50 UTC, nuradiyana commented on database/migrations/testing/2024_10_21_085431_create_donations_table.php
File name nya jadi `create_donations_table.php` aja

2024-10-28 09:50 UTC, nuradiyana commented on src/DistributionFinancingServiceProvider.php
>              ->hasConfigFile('financing');
Ini tambahkan `hasMigration('create_distribution_financings_table')`

2024-10-28 09:50 UTC, nuradiyana commented on src/DistributionFinancingServiceProvider.php
>              ->hasConfigFile('financing');
Bisa cek ini 

https://github.com/spatie/laravel-package-tools?tab=readme-ov-file#working-with-migrations

2024-10-28 09:58 UTC, nadiannisaqilah commented on src/DistributionFinancingServiceProvider.php
>              ->hasConfigFile('financing');
Oiya lupa

2024-10-28 10:15 UTC, nuradiyana commented on routes/api.php
> +};
Ini dalem banget nis langsung gini aja

```php
// use ke Facade Route

Route::middleware('auth:sanctum')->group(function (Router $router): void {
         $router->post('/distribution/project/financing', [Controllers\FinancingController::class, 'store']);

         $router->get('/distribution/project/financing/donation', [Controllers\FinancingController::class, 'index']);
         $router->delete('/distribution/project/financing/{financing}', [Controllers\FinancingController::class, 'delete']);
    });
```

2024-10-29 00:46 UTC, nuradiyana approved these changes

2024-10-29 00:46 UTC, merged